### ISSUE TITLE
?

### ISSUE THREAD

**Issue by DeletedUser575703f6** [RainKavik-Group/genshin-hdiff-patch-gui#3]
![image](https://user-images.githubusercontent.com/86580312/200314472-b82a1bde-4be1-4e55-89fe-01638a52a1ea.png)

**Comment by sdy623** [comment]
This is the problem caused by the Windows default encoding. This tool is set for a encoding as 'GBK', a decoding mainly used in Simplified Chinese. For your device using 'BIG5' encoding, it will probably cause Mojibake problem. To fix this, you should edit the tool's source code.

**Comment by MLChinoo** [comment]
> This is the problem caused by the Windows default encoding. This tool is set for a encoding as 'GBK', a decoding mainly used in Simplified Chinese. For your device using 'BIG5' encoding, it will probably cause Mojibake problem. To fix this, you should edit the tool's source code.

Actually not lmao :D 
It's my fault that it would still check the audio path even if you don't check the audio button sry
It has been fixed (maybe) by @sdy623
